version: '3'
services:
  api:
    container_name: api
    build: .
    ports:
    - "5000:5000"
    expose:
    - 5000
    volumes:
    - .:/code
    depends_on:
    - db
    links:
    - db
    networks:
    - frontend
  db:
    image: "postgres"
    expose:
    - 5432
    environment:
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB: "${PGDATABASE}"
      POSTGRES_USER: postgres
