require('dotenv').config()
const express = require('express')
const app = express()
const bodyParser = require('body-parser')
const multer = require('multer')
const cors = require('cors')
const upload = multer({ dest: 'public/photos' })
const cookieParser = require('cookie-parser')
const helmet = require('helmet')

require('./scripts/wait-for-postgres')

app.use(helmet())
app.use(cors())
app.use(cookieParser())
app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())

app.post('/upload', upload.single('file'), require('./controllers/upload'))
app.post('/webhook', require('./controllers/webhook'))
app.post('/user', require('./controllers/create-user'))
app.get('/tries', require('./controllers/tries'))
app.get('/identify', require('./controllers/identify'))

app.use(express.static('public'))
app.listen(5000)